<?php

/**
 * ProcessWire Super Smartypants Textformatter
 *
 * See: http://daringfireball.net/projects/smartypants/ 
 * 
 * ProcessWire 2.x
 *
 * Copyright (C) 2014 by Pierre-Luc Auclair
 * Licensed under The MIT License (MIT), see README.md
 *
 * Original ProcessWire module
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class TextformatterSuperSmartypants extends Textformatter {

	public static function getModuleInfo() {
		return array(
			'title' => 'SuperSmartyPants Typographer', 
			'version' => 100,
			'summary' => "Super Smartypants is a drop-in replacement for Smartypants core which adds language support and fine-tuned configuration for each language. Requires language module.",
			'url' => 'https://github.com/plauclair/SuperSmartypants',
		); 
	}

	public function format(&$str) {
		require_once("smartypants.php");
		$str = SmartyPants($str);
	}
}
